apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-demo-dev
spec:
  template:
    spec:
      containers:
      - name: my-app-image
        image: us-docker.pkg.dev/cloudrun/container/hello 
